### ISSUE TITLE
How should the dashboard send API authorization?

### ISSUE THREAD

**Issue by groovecoder** [mozilla-services/push-messages#5]
When dev dashboard POSTs a new key to this API, we should send authorization, so we don't allow all HTTP POSTs to start recording messages.

**Comment by bbangert** [comment]
I was planning on letting ops restrict access to this machine from within its AWS security group. @oremj, would that be an appropriate restriction on this API?

**Comment by oremj** [comment]
That seems fine to me, assuming only other AWS resources will need to access this internal API. @jvehent thoughts?

**Comment by jvehent** [comment]
I don't have the context to answer, is there a diagram somewhere?
Is this an internal-only API for push, that will sit behind other components that provide authentication?

**Comment by groovecoder** [comment]
Here's a diagram as I currently understand it. We're adding the bottom half of this diagram to get messages out of the existing dyanamo db. The green arrow is pointing at the API connection we're talking about.

So, yes ...
1. This new messages.push.services.mozilla.com API will/can be internal.
2. The developer.services.mozilla.com component makes the user authenticate and authorize the requests to the internal API. 

![dev-dash-messages-api](https://cloud.githubusercontent.com/assets/71928/13674386/eab221e4-e6a2-11e5-8d82-17cc4761778f.png)

**Comment by jvehent** [comment]
+:100: for the diagram!

I think as long as we have a 1:1 relationship between the two services, authentication is unnecessary. When we start opening `messages.p.s.m.c` to other frontends, authentication (hawk, really) is a good way to lock down who can do what, and keep accurate logs.

So, I'm +1 on the security group approach for now.

**Comment by bbangert** [comment]
Closing for use of a SG for now.
