### ISSUE TITLE
Change status code to 204 when GET /messages/{key} is empty

### ISSUE THREAD

**Issue by groovecoder** [mozilla-services/push-messages#6]
Steps to reproduce:
1. GET /messages/{key} for a {key} value that has no messages

Expected results:
Respond with 204 status code

Actual results:
Response with 404 status code

404 indicates the key does not exist in the system; 204 would indicate that it exists, but there are no messages for it.

**Comment by bbangert** [comment]
Is it ok to always return a 404? Alternatively, I can fabricate a different link when registering a key that I can validate independently of a database so that I can return a 204 for valid links that have had keys registered, and 404 otherwise.

**Comment by groovecoder** [comment]
I need to know if 1. there are no messages to display because the key is not recording, or 2. the key is recording, but there are no messages to display because there are no messages.

I need to know so I can put the user back thru the "(re-)validate your VAPID key" flow.

So, you could return 404 but there would need to be something in the response body or headers indicating that the key is actually recording. But at that point you've already implemented the logic for it, so returning a 204 status code seems like a better fit.

**Comment by bbangert** [comment]
Can't you get the keylist to find out if the key is being recorded?

**Comment by groovecoder** [comment]
Yes, which is probably good enough for launch...

So turn this ... 
1. POST /keys
   `
     {"public-key": "key"}
   `
   - 201 Created
2. GET /messages/{key}
   - 404 Not Found
3. Show "no messages"

into this ...
1. POST /keys
   `
     {"public-key": "key"}
   `
   - 201 Created
2. GET /messages/{key}
   - 404 Not Found
3. GET /keys
   - 200 OK
   - If {key} in keys, show "no messages"
     - Else, show "unknown key, please re-validate"

:question:

**Comment by bbangert** [comment]
Oh, I was mainly trying to avoid extra hits to key lookup. I guess it's not that big of a deal, I'll change the status so you don't need to add any more calls.

**Comment by groovecoder** [comment]
Cool, thanks.

**Comment by bbangert** [comment]
Is it ok if this change means in the remote case that the Redis cluster is lost, your app will need to re-register public keys? That seems like a rare enough event that it should be ok. If so, that'd simplify quite a few things in push_messages as well, so hopefully that'll be ok.

**Comment by groovecoder** [comment]
I would say yes ... maybe ... for now. We're learning that registering and validating public keys will be the biggest pain in the ass for devs to do VAPID.

In the clunky copy-paste UX/UI of the dashboard, the various languages and libraries are really tough to export/import keys appropriately. :cry: 

How remote are the chances that the Redis cluster will be lost? Can we add some extra precautions to make it as remote as possible?
